services:
  - type: web
    name: paycore-backend
    runtime: docker
    plan: free
    region: singapore
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeployTrigger: commit
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: paycore-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: paycore-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: paycore-db
          property: password
      - key: SPRING_DATASOURCE_DRIVER
        value: org.postgresql.Driver
      - key: SPRING_JPA_DIALECT
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: CORS_ALLOWED_ORIGINS
        value: https://paycore-frontend-live.onrender.com
